services:
  # Backend service
  backend:
    build:
      context: ./web-backend
      dockerfile: Dockerfile
    container_name: m3u8-converter-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
    volumes:
      # Mount volumes for temporary files
      - backend_uploads:/tmp/uploads
      - backend_downloads:/tmp/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: m3u8-converter-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_BACKEND_API_URL=${BACKEND_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_uploads:
    driver: local
  backend_downloads:
    driver: local

networks:
  default:
    name: m3u8-converter-network